name:Jamala Family 
home
on:App detector:ture:<or>:fake:
user:name:
  password:XXXX:
    runs-on:login:
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
